#!/bin/bash
#
# Quick Script to Create SFTP users
#
#######################################

## Setup
clear
echo 'Client FTP Generator'
echo ''

# Location
path='/mnt/Storage/___CLIENT_FTPS'
bupath='/mnt/Storage/___CLIENT_FTPS/backups'

# variables
path='/SAN/ISOLATED/INSECURE/CLIENT_FTPS'
bupath='/SAN3/CLIENT_FTP_SETUP'
ip=$(dig +short myip.opendns.com @resolver1.opendns.com)

## USER INPUT
echo ''
echo 'Hello, enter client login name (underscores for spaces)'
echo ''
read username
clear
echo ''
echo 'Enter comment for this account'
echo ''
read comment

## PASSWORD GENERATION
password=$(head /dev/urandom | tr -dc A-Za-z0-9 | head -c 13)

## USER CREATION
useradd -g clients -s /sbin/nologin -m -d $path/$username $username -c "$comment"
echo "$password" | passwd "$username"  --stdin
chown root:root $path/$username
chmod 755 $path/$username

## Save Data
echo 'Username: '$username >> $bupath/$username.txt
echo 'Password: '$password >> $bupath/$username.txt
echo 'Home: '$path/$username >> $bupath/$username.txt
echo 'Comment: '$comment >> $bupath/$username.txt

## DATA FOR USER
clear
echo ''
echo 'Copy & Paste to Email'
echo ''
echo '#######################'
echo 'Username is: '$username
echo 'Password is: '$password
echo ''
echo 'IP Address is: '$ip
echo 'Protocol is: SFTP'
echo '#######################'
echo ''
echo 'Copy postings to user Home SFTP directory: '$path/$username
echo ''
echo 'Comment: '$comment
echo ''
echo ''
